### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mathiasrabe** [dparrini/python-comtrade#4] opened 2019-07-18 07:38 UTC
I received some new ASCII Comtrade files, so I could test the ASCII parser. With the last commit from May 2, 2019 it worked good but with the current commit on master I get this error:

```
 File "comtrade.py", line 937, in parse
    self.status[i][line_number - 1] = svalues[i]

IndexError: list index out of range
```
So I changed this line

https://github.com/dparrini/python-comtrade/blob/d17ab5424e79add93c28538dac3175a3d3d4335a/comtrade.py#L924

to this:

`svalues = [int(x) for x in values[len(values)-status_count:]]`

**Comment by dparrini** [comment] 2020-07-04 22:04
I accepted and merged your solution, but did other small updates. Let me know if the issue is solved. Thanks!

**Closed** 2020-11-12 00:52 UTC
